spring:
  application:
    name: microshop-coupons

  datasource:
    url: jdbc:mysql://localhost:3306/microshop_sms
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 7000