spring:
  application:
    name: microshop-products

  datasource:
    url: jdbc:mysql://localhost:3306/microshop_pms
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
